apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vote
  labels:
    role: vote
spec:
  replicas: 4 
  minReadySeconds: 20
  selector:
    matchLabels:
      role: vote
    matchExpressions:
      - key: version
        operator: Exists
      - { key: version, operator: In, values: [v1, v2] }
  template: 
    metadata:
      name: vote 
      labels: 
        app: python 
        role: vote 
        version: v1 
    spec:
      containers: 
        - name: app 
          image: schoolofdevops/vote:v1 
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits: 
              memory: "128Mi"
              cpu: "250m"




